name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Setup key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
            key: ${{ secrets.TEST_KEY }} 
            known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
            
      # ...
      - name: Adding Known Hosts
        run: ssh-keyscan -H 178.170.47.43 >> ~/.ssh/known_hosts
      # Build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        # Deploy
      - name: Rsync Deployments Action
        uses: Burnett01/rsync-deployments@5.0
        with:
          switches: -avzr --delete
          path: ./build
          remote_path: /var/www/bt/build/
          remote_host: 178.170.47.43
          remote_user: root
          remote_key: ${{ secrets.TEST_KEY }}
